<a href="https://colab.research.google.com/github/AdityaTheEmpire/MLLAB/blob/main/MLEXP6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.preprocessing import LabelEncoder

fruits = ['Apple', 'Orange', 'Banana', 'Carrot', 'Tomato', 'Potato']
fruit_types = ['Fruit', 'Fruit', 'Fruit', 'Vegetable', 'Vegetable', 'Vegetable']

le = LabelEncoder()

encoded_types = le.fit_transform(fruit_types)

print('Original Data:', fruit_types)
print('Encoded Data:', encoded_types)


from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(['red', 'blue', 'green', 'blue', 'red']).reshape(-1, 1)

onehot_encoder = OneHotEncoder(sparse_output=False)

encoded_data = onehot_encoder.fit_transform(data)
print(encoded_data)



Original Data: ['Fruit', 'Fruit', 'Fruit', 'Vegetable', 'Vegetable', 'Vegetable']
Encoded Data: [0 0 0 1 1 1]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
